"""Baseline inicial - schema completo

Revision ID: e0f23250f3e7
Revises: 
Create Date: 2026-07-30 02:23:44.577581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f23250f3e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('motivos_cancelamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postos_graduacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('subunidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('admin', 'usuario', name='tipo_usuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('subunidade_id', sa.Integer(), nullable=True),
    sa.Column('posto_graduacao_id', sa.Integer(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('tentativas_login', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['posto_graduacao_id'], ['postos_graduacoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subunidade_id'], ['subunidades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_posto_graduacao_id'), ['posto_graduacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_subunidade_id'), ['subunidade_id'], unique=False)

    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf_usuario', sa.String(length=14), nullable=False),
    sa.Column('local', sa.String(length=255), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.Column('data_saida', sa.DateTime(), nullable=False),
    sa.Column('data_retorno', sa.DateTime(), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('endereco_destino', sa.Text(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('agendada', 'em_transito', 'retornado', 'cancelado', 'finalizado', name='status_saida'), nullable=False),
    sa.Column('status_atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(length=150), nullable=True),
    sa.Column('obs_cancelamento', sa.String(length=200), nullable=True),
    sa.Column('data_cancelamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cpf_usuario'], ['usuarios.cpf'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_cpf_usuario'), ['cpf_usuario'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_data_retorno'), ['data_retorno'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_data_saida'), ['data_saida'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_status'), ['status'], unique=False)

    op.create_table('solicitacoes_posto_graduacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('posto_atual_id', sa.Integer(), nullable=True),
    sa.Column('posto_solicitado_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('justificativa', sa.String(length=255), nullable=True),
    sa.Column('resposta_obs', sa.String(length=255), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('respondido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['posto_atual_id'], ['postos_graduacoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['posto_solicitado_id'], ['postos_graduacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondido_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacoes_posto_graduacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitacoes_posto_graduacao_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_posto_graduacao_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes_posto_graduacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacoes_posto_graduacao_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_posto_graduacao_status'))

    op.drop_table('solicitacoes_posto_graduacao')
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_status'))
        batch_op.drop_index(batch_op.f('ix_registros_data_saida'))
        batch_op.drop_index(batch_op.f('ix_registros_data_retorno'))
        batch_op.drop_index(batch_op.f('ix_registros_cpf_usuario'))

    op.drop_table('registros')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_subunidade_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_posto_graduacao_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_cpf'))

    op.drop_table('usuarios')
    op.drop_table('subunidades')
    op.drop_table('postos_graduacoes')
    op.drop_table('motivos_cancelamento')
    op.drop_table('config_sistema')
    # ### end Alembic commands ###
